/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

@SuppressWarnings("nls")
public final class AArgList extends PArgList
{
    private PExpression _expression_;
    private final LinkedList<PMoreListArguments> _moreListArguments_ = new LinkedList<PMoreListArguments>();

    public AArgList()
    {
        // Constructor
    }

    public AArgList(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _moreListArguments_)
    {
        // Constructor
        setExpression(_expression_);

        setMoreListArguments(_moreListArguments_);

    }

    @Override
    public Object clone()
    {
        return new AArgList(
            cloneNode(this._expression_),
            cloneList(this._moreListArguments_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgList(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PMoreListArguments> getMoreListArguments()
    {
        return this._moreListArguments_;
    }

    public void setMoreListArguments(List<?> list)
    {
        for(PMoreListArguments e : this._moreListArguments_)
        {
            e.parent(null);
        }
        this._moreListArguments_.clear();

        for(Object obj_e : list)
        {
            PMoreListArguments e = (PMoreListArguments) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._moreListArguments_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._moreListArguments_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._moreListArguments_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PMoreListArguments> i = this._moreListArguments_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMoreListArguments) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
