/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

@SuppressWarnings("nls")
public final class AArgArgument extends PArgument
{
    private PIdentifier _identifier_;
    private final LinkedList<PAssignValue> _assignValue_ = new LinkedList<PAssignValue>();
    private final LinkedList<PMoreArguments> _moreArguments_ = new LinkedList<PMoreArguments>();

    public AArgArgument()
    {
        // Constructor
    }

    public AArgArgument(
        @SuppressWarnings("hiding") PIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _assignValue_,
        @SuppressWarnings("hiding") List<?> _moreArguments_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setAssignValue(_assignValue_);

        setMoreArguments(_moreArguments_);

    }

    @Override
    public Object clone()
    {
        return new AArgArgument(
            cloneNode(this._identifier_),
            cloneList(this._assignValue_),
            cloneList(this._moreArguments_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgArgument(this);
    }

    public PIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PAssignValue> getAssignValue()
    {
        return this._assignValue_;
    }

    public void setAssignValue(List<?> list)
    {
        for(PAssignValue e : this._assignValue_)
        {
            e.parent(null);
        }
        this._assignValue_.clear();

        for(Object obj_e : list)
        {
            PAssignValue e = (PAssignValue) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._assignValue_.add(e);
        }
    }

    public LinkedList<PMoreArguments> getMoreArguments()
    {
        return this._moreArguments_;
    }

    public void setMoreArguments(List<?> list)
    {
        for(PMoreArguments e : this._moreArguments_)
        {
            e.parent(null);
        }
        this._moreArguments_.clear();

        for(Object obj_e : list)
        {
            PMoreArguments e = (PMoreArguments) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._moreArguments_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._assignValue_)
            + toString(this._moreArguments_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._assignValue_.remove(child))
        {
            return;
        }

        if(this._moreArguments_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        for(ListIterator<PAssignValue> i = this._assignValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAssignValue) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMoreArguments> i = this._moreArguments_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMoreArguments) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
