/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

@SuppressWarnings("nls")
public final class ARule3Statement extends PStatement
{
    private PExpression _exp1_;
    private final LinkedList<PMoreExpressions> _moreExpressions_ = new LinkedList<PMoreExpressions>();

    public ARule3Statement()
    {
        // Constructor
    }

    public ARule3Statement(
        @SuppressWarnings("hiding") PExpression _exp1_,
        @SuppressWarnings("hiding") List<?> _moreExpressions_)
    {
        // Constructor
        setExp1(_exp1_);

        setMoreExpressions(_moreExpressions_);

    }

    @Override
    public Object clone()
    {
        return new ARule3Statement(
            cloneNode(this._exp1_),
            cloneList(this._moreExpressions_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule3Statement(this);
    }

    public PExpression getExp1()
    {
        return this._exp1_;
    }

    public void setExp1(PExpression node)
    {
        if(this._exp1_ != null)
        {
            this._exp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp1_ = node;
    }

    public LinkedList<PMoreExpressions> getMoreExpressions()
    {
        return this._moreExpressions_;
    }

    public void setMoreExpressions(List<?> list)
    {
        for(PMoreExpressions e : this._moreExpressions_)
        {
            e.parent(null);
        }
        this._moreExpressions_.clear();

        for(Object obj_e : list)
        {
            PMoreExpressions e = (PMoreExpressions) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._moreExpressions_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp1_)
            + toString(this._moreExpressions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp1_ == child)
        {
            this._exp1_ = null;
            return;
        }

        if(this._moreExpressions_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp1_ == oldChild)
        {
            setExp1((PExpression) newChild);
            return;
        }

        for(ListIterator<PMoreExpressions> i = this._moreExpressions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMoreExpressions) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
