/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class ARule1Comparison extends PComparison
{
    private PExpression _exp1_;
    private PExpression _exp2_;

    public ARule1Comparison()
    {
        // Constructor
    }

    public ARule1Comparison(
        @SuppressWarnings("hiding") PExpression _exp1_,
        @SuppressWarnings("hiding") PExpression _exp2_)
    {
        // Constructor
        setExp1(_exp1_);

        setExp2(_exp2_);

    }

    @Override
    public Object clone()
    {
        return new ARule1Comparison(
            cloneNode(this._exp1_),
            cloneNode(this._exp2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule1Comparison(this);
    }

    public PExpression getExp1()
    {
        return this._exp1_;
    }

    public void setExp1(PExpression node)
    {
        if(this._exp1_ != null)
        {
            this._exp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp1_ = node;
    }

    public PExpression getExp2()
    {
        return this._exp2_;
    }

    public void setExp2(PExpression node)
    {
        if(this._exp2_ != null)
        {
            this._exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp1_)
            + toString(this._exp2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp1_ == child)
        {
            this._exp1_ = null;
            return;
        }

        if(this._exp2_ == child)
        {
            this._exp2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp1_ == oldChild)
        {
            setExp1((PExpression) newChild);
            return;
        }

        if(this._exp2_ == oldChild)
        {
            setExp2((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
