/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.analysis;

import java.util.*;
import minipython.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACmdsGoal(ACmdsGoal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncCommands(AFuncCommands node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStmtCommands(AStmtCommands node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncFunction(AFuncFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArgArgument(AArgArgument node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignValue(AAssignValue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoreArguments(AMoreArguments node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule1Statement(ARule1Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule2Statement(ARule2Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule3Statement(ARule3Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule4Statement(ARule4Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule5Statement(ARule5Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule6Statement(ARule6Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule7Statement(ARule7Statement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoreExpressions(AMoreExpressions node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule2Expression(ARule2Expression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule3Expression(ARule3Expression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExpression(AMultExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAddExpression(AAddExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusExpression(AMinusExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValueExpression(AValueExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdExpression(AIdExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncExpression(AFuncExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpExpression(AExpExpression node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoreValues(AMoreValues node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValueMultiplication(AValueMultiplication node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplicationMultiplication(AMultiplicationMultiplication node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule1Comparison(ARule1Comparison node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule2Comparison(ARule2Comparison node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARule3Comparison(ARule3Comparison node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFunctionCall(AFunctionCall node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArgList(AArgList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMoreListArguments(AMoreListArguments node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberValue(ANumberValue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringValue(AStringValue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntNumber(AIntNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentifier(AIdentifier node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTab(TTab node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExMark(TExMark node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssign(TAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEquals(TEquals node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGrt(TGrt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGte(TGte node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLt(TLt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLte(TLte node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLeftPar(TLeftPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRightPar(TRightPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSquareRightBr(TSquareRightBr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSquareLeftBr(TSquareLeftBr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemi(TSemi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhile(TWhile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFor(TFor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrint(TPrint node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTReturn(TReturn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDef(TDef node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTrue(TTrue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFalse(TFalse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLineComment(TLineComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInteger(TInteger node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
